### ISSUE TITLE
'IntEditText' not found and bunch of other errors

### ISSUE THREAD

**Issue by sukhchain9935** [EdgarReynaldo/EagleGUI#2]
I did a find search on the whole project but I couldn't find 'IntEditText' anywhere. The other example was compiling fine before.

[Edit]:
The other example which is about drawing rectangles with mouse is still working fine.

`mingw32-make new
g++ -o ../bin/examples/example example.cpp -I ../include ../lib/libEagle.a ../lib/libEagleA5.a
In file included from ../include/Eagle.hpp:34,
                 from ../include/Eagle/backends/Allegro5Backend.hpp:28,
                 from example.cpp:4:
../include/Eagle/Area.hpp:270:2: warning: #warning Eagle::Rectangle has issues with OpenGL headers [-Wcpp]
 #warning Eagle::Rectangle has issues with OpenGL headers
  ^~~~~~~
In file included from ../include/Eagle.hpp:36,
                 from ../include/Eagle/backends/Allegro5Backend.hpp:28,
                 from example.cpp:4:
../include/Eagle/Clipboard.hpp:29:2: warning: #warning TODO : Support more than local strings... Use my clipboard library instead. [-Wcpp]
 #warning TODO : Support more than local strings... Use my clipboard library instead.
  ^~~~~~~
example.cpp: In function 'int main(int, char**)':
example.cpp:117:4: error: 'IntEditText' was not declared in this scope
    IntEditText numinput;
    ^~~~~~~~~~~
example.cpp:117:4: note: suggested alternative: 'EditText'
    IntEditText numinput;
    ^~~~~~~~~~~
    EditText
example.cpp:118:4: error: 'numinput' was not declared in this scope
    numinput.SetupText("" , font , HALIGN_RIGHT , VALIGN_CENTER);
    ^~~~~~~~
example.cpp:118:4: note: suggested alternative: 'Input'
    numinput.SetupText("" , font , HALIGN_RIGHT , VALIGN_CENTER);
    ^~~~~~~~
    Input
example.cpp:152:11: error: 'class BasicTextButton' has no member named 'SetupText'; did you mean 'SetOurText'?
    clrbtn.SetupText("Clear" , font , HALIGN_CENTER , VALIGN_CENTER);
           ^~~~~~~~~
           SetOurText
example.cpp:165:4: error: 'BasicCheckBox' was not declared in this scope
    BasicCheckBox cbox[2];
    ^~~~~~~~~~~~~
example.cpp:165:4: note: suggested alternative: 'BasicIcon'
    BasicCheckBox cbox[2];
    ^~~~~~~~~~~~~
    BasicIcon
example.cpp:168:4: error: 'cbox' was not declared in this scope
    cbox[0].SetButtonState(false , false , false);
    ^~~~
example.cpp:168:4: note: suggested alternative: 'cos'
    cbox[0].SetButtonState(false , false , false);
    ^~~~
    cos
example.cpp:185:17: error: 'class BasicTextButton' has no member named 'SetupText'; did you mean 'SetOurText'?
    send_btns[0].SetupText("Kill" , font , HALIGN_CENTER , VALIGN_CENTER , 2 , 2);
                 ^~~~~~~~~
                 SetOurText
example.cpp:186:17: error: 'class BasicTextButton' has no member named 'SetupText'; did you mean 'SetOurText'?
    send_btns[1].SetupText("Chase" , font , HALIGN_CENTER , VALIGN_CENTER , 2 , 2);
                 ^~~~~~~~~
                 SetOurText
example.cpp:187:17: error: 'class BasicTextButton' has no member named 'SetupText'; did you mean 'SetOurText'?
    send_btns[2].SetupText("No Retreat" , font , HALIGN_CENTER , VALIGN_CENTER , 2 , 2);
                 ^~~~~~~~~
                 SetOurText
example.cpp:188:17: error: 'class BasicTextButton' has no member named 'SetupText'; did you mean 'SetOurText'?
    send_btns[3].SetupText("Send" , font , HALIGN_CENTER , VALIGN_CENTER , 2 , 2);
                 ^~~~~~~~~
                 SetOurText
example.cpp:190:15: error: use of deleted function 'FlowLayout::FlowLayout()'
    FlowLayout flow;
               ^~~~
In file included from ../include/Eagle/Gui/Layouts.hpp:35,
                 from ../include/Eagle/Gui.hpp:40,
                 from ../include/Eagle.hpp:48,
                 from ../include/Eagle/backends/Allegro5Backend.hpp:28,
                 from example.cpp:4:
../include/Eagle/Gui/Layout/FlowLayout.hpp:52:7: note: 'FlowLayout::FlowLayout()' is implicitly deleted because the default definition would be ill-formed:
 class FlowLayout : public LayoutBase {/// TODO : IMPLEMENT ME!
       ^~~~~~~~~~
../include/Eagle/Gui/Layout/FlowLayout.hpp:52:7: error: no matching function for call to 'LayoutBase::LayoutBase()'
In file included from ../include/Eagle/Gui/WidgetHandler.hpp:35,
                 from ../include/Eagle/Gui.hpp:33,
                 from ../include/Eagle.hpp:48,
                 from ../include/Eagle/backends/Allegro5Backend.hpp:28,
                 from example.cpp:4:
../include/Eagle/Gui/Layout/Layout.hpp:106:4: note: candidate: 'LayoutBase::LayoutBase(std::__cxx11::string, std::__cxx11::string)'
    LayoutBase(std::string objclass , std::string objname);
    ^~~~~~~~~~
../include/Eagle/Gui/Layout/Layout.hpp:106:4: note:   candidate expects 2 arguments, 0 provided
../include/Eagle/Gui/Layout/Layout.hpp:59:7: note: candidate: 'LayoutBase::LayoutBase(const LayoutBase&)'
 class LayoutBase : public WidgetBase {
       ^~~~~~~~~~
../include/Eagle/Gui/Layout/Layout.hpp:59:7: note:   candidate expects 1 argument, 0 provided
example.cpp:193:13: error: 'class BasicTextButton' has no member named 'SetPreferredSize'
       pbtn->SetPreferredSize();
             ^~~~~~~~~~~~~~~~
mingw32-make: *** [Makefile:7: new] Error 1
`

**Comment by EdgarReynaldo** [comment]
IntEditText is from EagleClassic.
