### ISSUE TITLE
License is AWOL

### ISSUE THREAD

**Issue by jacmoe** [EdgarReynaldo/EagleGUI#3]
You probably haven't noticed that the license text file is not present in the master branch.

The one I found looks like something akin to the Unlicense, am I right?

If so, then perhaps consider adding the Unlicense license through the Github web interface?

It would then be officially recognized.

Not a big deal, though ;)

**Comment by SamuelMarks** [comment]
Found it: https://github.com/EdgarReynaldo/EagleGUI/blob/9cc1224/docs/src/EagleLicense.txt

**Comment by EdgarReynaldo** [comment]
Sorry for the abhorrent delay in my response. I wasn't aware I even had any issues open.

The license now resides here :
https://github.com/EdgarReynaldo/EagleGUI/blob/master/docs/src/EagleLicense.txt

**Comment by SamuelMarks** [comment]
@Edgar-Reynaldo FYI: If you put it in the root directory it shows up in the GitHub sidebar, API, and search results.

(I think name it "LICENSE.txt")

Works better if you use a known license, like [zlib](https://en.wikipedia.org/wiki/Zlib_License) or [CC0](https://creativecommons.org/share-your-work/public-domain/cc0).

**Comment by EdgarReynaldo** [comment]
@SamuelMarks 
Thank you for the heads up. I think zlib license is appropriate here, or maybe LGPL. I will use the zlib license for now and consider LGPL in the future.

**Comment by EdgarReynaldo** [comment]
@SamuelMarks I changed my mind and went with Mozilla Public License v2.0 as it is still free to use and distribute as long as the source code form is made available.

https://github.com/EdgarReynaldo/EagleGUI/blob/master/LICENSE

**Comment by SamuelMarks** [comment]
Awww but zlib is prettier

I use Apache/MIT more often though…
